server:
  port: 8079
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: 123456
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

# 15,000,000 ~ 800,000,000, there is 785,000,000
generating-id-num:
  increment: 10
  minimumThreshold: 4
  start: 15000000
  end: 800000000
